import React from 'react';
import {AbsoluteFill,interpolate,useCurrentFrame} from 'remotion';
import {C} from './config';
export const clamp={extrapolateLeft:'clamp',extrapolateRight:'clamp'} as const;
export const Shell:React.FC<{chapter:string;title:string;sub?:string;children?:React.ReactNode}> = ({chapter,title,sub,children})=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:C.bg,color:C.white,fontFamily:'Arial, sans-serif',padding:'145px 90px 200px',backgroundImage:'radial-gradient(ellipse at 85% 15%, #18303a 0%, transparent 55%)'}}>
<div style={{display:'flex',justifyContent:'space-between',fontSize:28,letterSpacing:3,color:C.muted}}><span>ORDERFL<span style={{color:C.buy}}>0</span>WTALKS</span><span>FIELD NOTES / 01</span></div>
<div style={{marginTop:95,opacity:interpolate(f,[0,10],[0,1],clamp),translate:`0px ${interpolate(f,[0,14],[24,0],clamp)}px`}}><div style={{color:C.amber,fontSize:28,letterSpacing:5,marginBottom:28}}>{chapter}</div><div style={{fontSize:88,fontWeight:800,lineHeight:1.03,letterSpacing:-3}}>{title}</div>{sub&&<div style={{fontSize:40,lineHeight:1.35,color:C.muted,marginTop:28}}>{sub}</div>}</div>
<div style={{marginTop:65,flex:1,opacity:interpolate(f,[6,18],[0,1],clamp)}}>{children}</div>
<div style={{position:'absolute',bottom:155,left:90,right:90,borderTop:`1px solid ${C.line}`,paddingTop:25,display:'flex',justifyContent:'space-between',fontSize:25,color:C.muted}}><span>@Orderfl0wTalks</span><span>ILLUSTRATIVE DATA</span></div>
</AbsoluteFill>};
export const Card:React.FC<{children:React.ReactNode}> = ({children})=><div style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:26,padding:38}}>{children}</div>;
export const Note:React.FC<{children:React.ReactNode;color?:string}>=({children,color=C.amber})=><div style={{fontSize:42,fontWeight:700,lineHeight:1.25,color,marginTop:35}}>{children}</div>;
export const Footprint:React.FC<{rows:number[][];side?:'buy'|'sell';active?:number;pulse?:number}> = ({rows,side='buy',active=-1,pulse=0})=><Card><div style={{display:'grid',gridTemplateColumns:'1.2fr 1fr 1fr',color:C.muted,fontSize:28,letterSpacing:2,paddingBottom:30}}><span>PRICE</span><span style={{textAlign:'right'}}>BID / SELL</span><span style={{textAlign:'right'}}>ASK / BUY</span></div>{rows.map((r,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'1.2fr 1fr 1fr',alignItems:'center',height:98,fontFamily:'Consolas, monospace',fontSize:49,borderTop:`1px solid ${C.line}`,background:i===active?'#243442':'transparent',borderLeft:`5px solid ${i===active?(side==='buy'?C.buy:C.sell):'transparent'}`,padding:'0 12px'}}><span style={{fontSize:36,color:C.muted}}>{r[0].toFixed(2)}</span>{[1,2].map(n=><span key={n} style={{textAlign:'right',color:n===1?C.sell:C.buy,fontWeight:700,scale:i===active&&n===(side==='buy'?2:1)?1+pulse*.12:1,opacity:.5+.5*r[n]/310}}>{r[n]}</span>)}</div>)}<div style={{marginTop:25,textAlign:'center',color:C.muted,fontSize:28}}>EXECUTED VOLUME · BID × ASK</div></Card>;
